/**
 * @typedef {Array} phraseBank
 * @description This is where we store all of our phrases that we want to use for bingo tiles.
 */

const phraseBank = [
  // "Leon says octothorpe",
  "Leon says 'automagically' \r✨✨✨✨",
  '10 people finish a challenge before the timer goes off ⏲️',
  'Leon mentions the OnlyFans page 🔞 ',
  // "Alissa posts a helpful link in chat 🔗",
  'Leon tells us what he is drinking today',
  'Hydrate! 🚰',
  'Posture Check!',
  "Don't call yourself a junior dev 🙅🏿",
  'One job please! 💰',
  // "community goal met 🎉",
  'Bob gets mentioned by Leon or slides',
  'Dylan spits hot fire 🔥🔥',
  'The Bachelor 🌹',
  'Bring It On 📣',
  'Blame the nuns!',
  // "Domino's 🍕",
  'Machi/Simba borks in the background 🐕',
  'Leon transforms into Little Leon',
  "It looks like we're going to run a little late",
  'Leon forgets and then remembers that bingo exists',
  'You messed up',
  // "Leon is amused by bootieliquor's name",
  "spend Jeff Bezos'/Andy's money! 💸",
  'Not that kind of stream, folx!',
  'Join us for office hours! 🕘',
  'We reach a level 5 hype train! 🚂',
  'Party Mode Activated! 🎊',
  // "Doggo Cam activated 🐶",
  // "You're a full stack dev now! 🏆",
  'Someone redeems soundboard alert 🔊',
  'First tryyy! 👍🏿',
  "We don't get got, we go get 😎",
  'Leon gets spicy 🌶️',
  "We're going to finish early today",
  'You remembered to check in on Twitter',
  "You're signed up for Leon's newsletter",
  "You're taking care of yourself 🛀🏾"
];
