const weeklyPhrases = [
  "Leon tells us about THE MACHINE 🐾",
  "Backend review class Sunday @ 1pm EST",
  "Stream & Blog team meeting @ 6:30pm EST",
  "Team project next week! 🤝",
  "Keep up with your networking 💬",
  "100 hours project due Tuesday 6/1",
  "Checklist due Tuesday 4/27 ✅",
  "Team project due Tuesday 5/4",
  "Hitlist due Tuesday 5/11 🎯",
  "Don't forget to take care of yourself! 🛀",
  "Keep pushing every day 🟩",
  "10 premium job applications due Tuesday 6/15 📝",
  "Prep the bank 🏦"
];
/*
const weekOnePhrases = [
    "The Golden Rule 👑👑👑",
    "What is the internet? 💻 🖥️",
    "angry Shia LaBeouf",
    "Hello world!",
    "Size doesn't matter, okay? OKAY???",
    "CSS is about <em>style</em>",
    "Ordered List",
    "Unordered List",
    `Syntax:
     Spelling and Grammar rules`,
    'Someone preemptively types "organization" in the chat 👩🏽‍💻',
    "Resetting the Forgetting Curve 😱",
    "What should go in the head tag?",
    "anchor tags are for links ⚓",
    "Progressive Enhancement"
  ]
*/

/*
const weekTwoPhrases = [
  "The Golden Rule: Seperation of Concerns 👑👑👑",
  "What is the internet? 💻 🖥️",
  "Hello twitch!",
  `Syntax:
   Spelling and Grammar rules`,
  'Someone preemptively types "organization" in the chat 👩🏽‍💻',
  "Resetting the Forgetting Curve 😱",
  "Progressive Enhancement!",
  // "Everyone freaks out about operators",
  "Repetition Repetition Repetition Repetition Repetition Repetition",
  "CSS link goes in the head 🗣️",
  "Don't know? Go to the MDN!",
  "Selectors are about relationships",
  "Only ONE id with the same value per document!",
  "Someone figures out the specificity before you even started",
  "You messed up"
]
*/

/*
const week3Phrases = [
  `The Golden Rule: Seperation of Concerns
  👑👑👑`,
  'Someone preemptively types "organization" in the chat 👩🏽‍💻',
  "CSS goes in a separate file",
  "Don't know? Go to the MDN!",
  "Get your selector relationships in order",
  "Only ONE id with the same value per document!",
  "Someone figures out the specificity before you even start",
  "Cascade - lower rules can override the ones above!",
  "The Box Model:  Content > Padding > Border > Margin",
  "We all float down here; you'll float too 🎈🎈🎈",
  "Get your shit together UPS",
  "Fluid: EVERYTHING IS A PERCENTAGE %%%",
  "Ems and Rems keep your font sizes elastic",
  "Flexbox is magic, y'all ✨✨✨",
  `<a href="http://css-tricks.com">css-tricks.com</a>: your CSS bible`,
  "Tried to use a media query without viewport <meta> tag",
  "Make good content decisions",
  "Today's stranger is tomorrow's coworker",
  "Insert unpaid meetup.com advertisement",
  "A lime alien that will haunt your dreams",
  "Spaced follow-up is important"
]
*/

// const week4Phrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   "Get your selector relationships in order",
//   "Only ONE id with the same value per document!",
//   "Someone figures out the specificity before you even start",
//   "Cascade - lower rules can override the ones above!",
//   "The Box Model:  Content > Padding > Border > Margin",
//   "We all float down here; you'll float too 🎈🎈🎈",
//   "Get your shit together UPS",
//   "Fluid: EVERYTHING IS A PERCENTAGE %%%",
//   "Ems and Rems keep your font sizes elastic",
//   "Flexbox is magic, y'all ✨✨✨",
//   `<a href="http://css-tricks.com">css-tricks.com</a>: your CSS bible`,
//   "Tried to use a media query without viewport <meta> tag",
//   "Make good content decisions",
//   "Stranger to coworker pipeline",
//   "Insert unpaid meetup.com advertisement",
//   "A lime alien that will life forever in your nightmares",
//   "Spaced follow-up is important",
//   "Progressive Enhancement",
//   "Khan Academy",
//   "Sh*t just got real 💩",
//   "Boats and logs 🚣🏽‍♀️",
//   "Make layouts 5-8 mobile responsive! 📱"
// ];

// const weekSevenPhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Stranger to coworker pipeline",
//   // "Insert unpaid meetup.com advertisement",
//   // "Computers do what you tell them to do",
//   // "Variables are buckets",
//   // "binary, upload, boom 👽",
//   // `Syntax:
//   // Spelling and Grammar rules`,
//   // "Declaration and then Assignment",
//   // "camelCase isOurConvention",
//   // "Leon misspelled 'oven'",
//   // "Everyone freaks out about operators",
//   "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "You come to the realization that Leon is NOT a lawyer ⚖️",
//   "Build an online presence",
//   "Unless you're a designer, use a portfolio template",
//   "Don't freelance without a contract! 📝",
//   "Under promise, over deliver! 📦"
// ];

// const weekEightPhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Computers do what you tell them to do",
//   "Variables are buckets",
//   "binary, upload, boom 👽",
//   `Syntax:
//   Spelling and Grammar rules`,
//   "Declaration and then Assignment",
//   "Everyone freaks out about operators",
//   // "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "Leon reveals house-specific office hours!",
//   "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by Feb 2!",
//   "Welcome back, we missed you! <br> Have a free space for being awesome! 😊"
// ];

// const weekNinePhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Computers do what you tell them to do",
//   "Variables are buckets",
//   // "binary, upload, boom 👽",
//   `Syntax:
//   Spelling and Grammar rules`,
//   "Declaration and then Assignment",
//   "Everyone freaks out about operators",
//   // "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   // "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by Feb 2!",
//   "Happy birthday, Alissa! 🎂",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎"
// ];

// const weekTenPhrases = [
//   // `The Golden Rule: Seperation of Concerns
//   // 👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by March 2!",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects!",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope!"
// ];

// const weekly11Phrases = [
//   // `The Golden Rule: Seperation of Concerns
//   // 👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   // "multiple conditions? Use && or ||",
//   "Beware the trough of sorrow!",
//   "Get a paid client by March 2!",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "Live portfolio review Friday @ 6:30EST! 🎙️",
//   "Leon announces the sponsor 🥳",
//   "Leon drops that sweet !Merch 👙",
//   "constructors are like factories 🏭",
//   "A prototype is another object that is used as a fallback source of properties",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API"
// ];

// const weekly12Phrases = [
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "Beware the trough of sorrow!",
//   "Don't forget to take care of your health! 💗",
//   "Repetition Repetition Repetition Repetition Repetition Repetition",
//   "Resetting the Forgetting Curve 😱",
//   "Let's GIT it on! 🥊",
//   "pwd shows where you are 📍",
//   "mkdir to create a new folder 📁",
//   "Git is a version control system",
//   "Save yourself by taking a snapshot(commit) in git 📸",
//   "You successfully installed git 🙌",
//   "Not sure what's in staging? git status",
//   "Uses branches so you don't BORK all your code 🐶",
//   "Github is more than backups!",
//   "You push a new repo",
//   "You can host with Github pages 🌐",
//   "Raffle time 🏆 Thanks for the swag, Microsoft!",
//   "Show all files in a folder using ls",
//   "remove a file with rm",
//   "git init creates a special folder to hold your commits",
//   "git add. adds everything to the staging area ➡️",
//   "don't be afraid to commit 💍"
// ];

// const weekly13Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "Live portfolio review Friday @ 6:30EST! 🎙️",
//   "Leon announces the sponsor 🥳",
//   "constructors are like factories 🏭",
//   "A prototype is another object that is used as a fallback source of properties",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "array.length lets you know how many elements are in your array",
//   "APIs are like restaurant menus",
//   "You can use local storage to store data across browser sessions! 💾"
// ];

// const weekl14Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "array.length lets you know how many elements are in your array",
//   "APIs are like restaurant menus",
//   "You can use local storage to store data across browser sessions! 💾",
//   "Bob and Nun emotes are here! Thanks, Wil!",
//   "Make sure to join our Code Wars clan ⚔️",
//   "Git Bowl this Saturday!",
//   "No class next week! 🗓️",
//   "Leon tells us about the new puppy 🐾",
//   "Contact NASA immediately! 🚀",
//   "War were declared 🃏"
// ];

// const week14bPhrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "APIs are like restaurant menus",
//   "Make sure to join our Code Wars clan ⚔️",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "The constructor keyword is used when you make a class",
//   "You create a detailed Pokemon class",
//   "You figure out how many rare candies you need to evolve your Pokemon 🍬"
// ];

// const week15Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   // "WHAT IS A STOPWATCH EVEN?",
//   // "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   // "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   // "Make sure you're using the right query parameters on your API",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Office hours moved to Sunday @ 1pm EST! 🕐",
//   "NERD FIGHT!!!! 👊🤓",
//   "The constructor keyword is used when you make a class",
//   "Construct an espresso machine ☕",
//   "OOP helps you understand existing code and add your own stuff with ease",
//   "Fuse data and functionality into one object with encapsulation, 👶🏾!",
//   "Want to hide details and show essentials? That's abstraction, 👶🏽!",
//   "WHAT WAS THE REASON?!"
// ];

// const week15bPhrases = [
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   // "WHAT IS A STOPWATCH EVEN?",
//   // "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Office hours moved to Sunday @ 1pm EST! 🕐",
//   "NERD FIGHT!!!! 👊🤓",
//   "The constructor keyword is used when you make a class",
//   "OOP helps you understand existing code and add your own stuff with ease",
//   "Fuse data and functionality into one object with encapsulation, 👶🏾!",
//   "Want to hide details and show essentials? That's abstraction, 👶🏽!",
//   "WHAT WAS THE REASON?!",
//   "You successfully create a class and extend it ",
//   "Networking starts up again next week",
//   "Inheritance lets us eliminate redundant code ",
//   "Yo dawg, I heard you like classes",
//   "We can use for...of in place of if/else and switch cases!"
// ];

// const week16Phrases = [
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "Classes are like templates for objects! 🧬",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Office hours moved to Sunday @ 1pm EST! 🕐",
//   "NERD FIGHT!!!! 👊🤓",
//   "The constructor keyword is used when you make a class",
//   "OOP helps you understand existing code and add your own stuff with ease",
//   "Fuse data and functionality into one object with encapsulation, 👶🏾!",
//   "Want to hide details and show essentials? That's abstraction, 👶🏽!",
//   "Creating new objects based on old ones? That's inheritance, 👶🏿",
//   "Want your code to work with a bunch of different objects? That's polymorphism, 👶🏻",
//   "Polymorphism allows us to override a method in every child class so it will do what we want",
//   "WHAT WAS THE REASON?! 🗣️",
//   "You successfully create a class and extend it ",
//   "Networking starts up again next week",
//   "Inheritance lets us eliminate redundant code ",
//   "Yo dawg, I heard you like classes",
//   "We can use for...of in place of if/else and switch cases!",
//   "You use encapsulation, abstraction, inheritance, and polymorphism 🦸🏾",
//   "Client deadline March 16th",
//   "Leon shares the big news! 😲"
// ];
// const week17aPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Review class this Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "NERD FIGHT!!!! 👊🤓",
//   "Client deadline March 16th",
//   "Don't forget to do your spaced repetition! 🔁",
//   "Use the form to join the Stream Team",
//   "Make sure to use The Checklist ✅",
//   "Make use of your Portfolio, Twitter, & LinkedIn 📁",
//   "You endorse at least 5 peers on LinkedIn",
//   "HITLIST is one of the most important career tools you have! 🎯",
//   "Each app should have a custom resume, cover letter, and story ",
//   "Take your interviewing skills to the BANK! 🏦",
//   "NO TIME TO BE HUMBLE DURING THE HUNT! 🤭",
//   "PREP for whiteboarding... Parameters, Returns, Examples, Pseudo Code",
//   "EUE during the interview... Explanation, Use, Example",
//   "Use CAR for the behavioral interview... Cause, Action Result",
//   "Your 100 Hours project should tie your past to present and show you can code ",
//   "Recruiters love 🟩",
//   "Research the company's process BEFORE the interview",
//   "Follow 50 engineers where you will be applying"
// ];
// const week17bPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live PREP class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "NERD FIGHT!!!! 👊🤓",
//   "You make an API request using async await",
//   "We were using APIs all along! 🤯",
//   "Don't forget to sign up for the Stream Team! 📹",
//   "Submit your checklist, 100 Hours Project, and Code Wars",
//   "JavaScript is single-threaded 🧵",
//   "Asyn allows us to continue using the app while operations are processed asyncronously",
//   "DOM is an API used to manipulate HTML/XML documents",
//   "We handle Web API responses with callbacks, promises, and async/await 📮",
//   "Higher Order Functions: function that takes another function as an argument",
//   "A Callback is a function that has be passed as an argument ☎️",
//   "Promises help us avoid Callback Hell 😈",
//   "Await waits for an async process to complete inside an Async Function",
//   "JS is sandboxed in the browser",
//   "Servers need disk access and network access 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️"
// ];

// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live PREP class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "NERD FIGHT!!!! 👊🤓",
//   "Get in that spaced repetition!",
//   "You make an API request using async await",
//   "We were using APIs all along! 🤯",
//   "Don't forget to sign up for the Stream Team! 📹",
//   "Submit your checklist, 100 Hours Project, and Code Wars",
//   "JavaScript is single-threaded 🧵",
//   "Asyn allows us to continue using the app while operations are processed asyncronously",
//   "DOM is an API used to manipulate HTML/XML documents",
//   "We handle Web API responses with callbacks, promises, and async/await 📮",
//   "Higher Order Functions: function that takes another function as an argument",
//   "A Callback is a function that has be passed as an argument ☎️",
//   "Promises help us avoid Callback Hell 😈",
//   "Await waits for an async process to complete inside an Async Function ⏳",
//   "JS is sandboxed in the browser",
//   "Servers need disk access and network access 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "The JavaScript is a lie! 🤥",
//   ".then() is a promise object that runs after the promise 'resolves'",
//   "Queues are FIFO (first in first out) structures",
//   "Callstack is a LIFO (last in first out) structure 🥞",
//   "You just got GOT!",
//   "JS is a language that can only do what the hosting environment allows 🌱",
//   "The same 💩 that lets you run JS in the browser can be used to run JS on servers, desktops, etc.",
//   "Clean up your back end! 🧼"
// ];

// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Tech Interveiw class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "NERD FIGHT!!!! 👊🤓",
//   "Get in that spaced repetition!",
//   "JavaScript is single-threaded 🧵",
//   "Higher Order Functions: function that takes another function as an argument",
//   "A Callback is a function that has be passed as an argument ☎️",
//   "Servers need disk access and network access 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Queues are FIFO (first in first out) structures",
//   "Callstack is a LIFO (last in first out) structure 🥞",
//   "You just got GOT!",
//   "JS is a language that can only do what the hosting environment allows 🌱",
//   "The same 💩 that lets you run JS in the browser can be used to run JS on servers, desktops, etc.",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js",
//   "Follow the key steps when making your API "
// ];

// const week19Phrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Tech Interveiw class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "Servers need disk access(FS) and network access(HTTP) 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js 🖼️",
//   "Follow the key steps when making your API 🔑",
//   "How does the internet work?",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "Push your server to Heroku",
//   "Start prepping THE BANK! 🏦"
// ];
// const week19aPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Project Night this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "Servers need disk access(FS) and network access(HTTP) 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js 🖼️",
//   "Follow the key steps when making your API 🔑",
//   "How does the internet work?",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "Push your server to Heroku",
//   "Start prepping THE BANK! 🏦"
// ];
// const week20Phrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Project Night this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "CRUD review Monday @ 6:30EST",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "Servers need disk access(FS) and network access(HTTP) 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js 🖼️",
//   "Follow the key steps when making your API 🔑",
//   "How does the internet work?",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "Push your server to Heroku",
//   "Start prepping THE BANK! 🏦",
//   "It's not too late!",
//   "Make a .env file and .gitignore to protect sensitive data"
// ];
// const week20bPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Don't forget to take care of yourself! 🛀",
//   "Get in that active recall and spaced repetition! 🔁",
//   "7 people from 100 Devs already have a job! 🤩",
//   "Microsoft Azure is a real one 🪟",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Follow the key steps when making your Passport/Express app 🔑",
//   "How does the internet work? 🌐",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "It's not too late! ⏳",
//   "Authentification = ability for users to login ✅",
//   "Microsoft Identity helps make signing in to your web apps easier",
//   "Azure Active Directory B2C lets you manage access on customer facing apps 🖥️",
//   "Mongoose provides a schema-based solution to model your app data",
//   "Models = fancy constructors complied from Schema definitions 🖼️",
//   "Passport = auth middleware for Node 🛂",
//   "MVC is a way to structure and organize our apps 🗂️"
// ];
// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Don't forget to take care of yourself! 🛀",
//   "Get in that active recall and spaced repetition! 🔁",
//   "7 people from 100 Devs already have a job! 🤩",
//   "Microsoft Azure is a real one 🪟",
//   "Follow the key steps when making your Passport/Express app 🔑",
//   "MongoDB stores your collections 🗄️",
//   "It's not too late! ⏳",
//   "Authentification = ability for users to login ✅",
//   "Microsoft Identity helps make sure you're not getting GOT by cyber security 🛡️",
//   "Azure Active Directory B2C lets you manage access on customer facing apps 🖥️",
//   "Mongoose provides a schema-based solution to model your app data",
//   "Models = fancy constructors complied from Schema definitions 🖼️",
//   "Passport = auth middleware for Node 🛂",
//   "MVC is a way to structure and organize our apps 🗂️",
//   "We don't get got, we go get 😎",
//   "You sign up for Microsoft 365 Developer Program (free!)",
//   "Passport has strategies 💡",
//   "Cookies store a session id in the user's browser to remember preferences 🍪"
// ];
