const weeklyPhrases = [
  'You volunteered your portfolio or resume for live review ✋',
  'Turn it up!',
  'Beware the Trough of Sorrow 📉',
  'You submitted your drafts and tasks in the form 📮',
  "You've already started using the SHEEEEEET",
  'Daily coding challenges starting! 🧩',
  'Get a paid client by March 31st 🤑',
  'functions are the building blocks of a program 🧱',
  'functions can take parameters and pass arguments',
  'Submit the best clip if you want to be fancy 📎',
  'A computer will do what you tell it to do',
  'Programming = writing instructions in a language a computer can understand',
  'Functions are reusuable sets of instructions',
  `Syntax:
  Spelling and Grammar rules`,
  'A variable is a bucket 🪣',
  'If statements are either true or false',
  'Conditional syntax uses if, else if, and else statements 🕵️',
  "Don't confuse assignment (=) and comparison (===)",
  '|| is the OR operator',
  'You code along in JavaScript 💻',
  '== compares only value,  === compares value AND type',
  '&& is the AND operator',
  'Multiple conditions?    Use && or || ',
  "You've had at least one coffee chat ☕",
  "You're keeping up with Anki 🗃️",
  'Loops repeat an action some number of times ➿',
  'for, while, and do while are the main types of loops',
  'Arrays are toasters 🍞',
  'Arrays have a zero-based index 0️⃣,1️⃣,2️⃣',
  'Arrays are a way to stored ordered collections',
  'Array elements can be of any type',
  'You can access and update elements in an array by their index position',
  'Arrays have lots of useful methods built in! 🔧',
  "Objects store 'keyed' collections",
  'JS Objects have properties (attributes) and methods (behaviors)',
  'Constructors are like factories 🏭',
  'A prototype is another object used as a fallback source of properties 💾',
  'Classes are like templates for objects!',
  'API = Application Programming Interface',
  'An API is a simple interface for some complex action',
  'Leon tries to make fetch happen 👚',
  "Grandma's car is now YOUR car! 🚗"
];
/*
const weekOnePhrases = [
    "The Golden Rule 👑👑👑",
    "What is the internet? 💻 🖥️",
    "angry Shia LaBeouf",
    "Hello world!",
    "Size doesn't matter, okay? OKAY???",
    "CSS is about <em>style</em>",
    "Ordered List",
    "Unordered List",
    `Syntax:
     Spelling and Grammar rules`,
    'Someone preemptively types "organization" in the chat 👩🏽‍💻',
    "Resetting the Forgetting Curve 😱",
    "What should go in the head tag?",
    "anchor tags are for links ⚓",
    "Progressive Enhancement"
  ]
*/

/*
const weekTwoPhrases = [
  "The Golden Rule: Seperation of Concerns 👑👑👑",
  "What is the internet? 💻 🖥️",
  "Hello twitch!",
  `Syntax:
   Spelling and Grammar rules`,
  'Someone preemptively types "organization" in the chat 👩🏽‍💻',
  "Resetting the Forgetting Curve 😱",
  "Progressive Enhancement!",
  // "Everyone freaks out about operators",
  "Repetition Repetition Repetition Repetition Repetition Repetition",
  "CSS link goes in the head 🗣️",
  "Don't know? Go to the MDN!",
  "Selectors are about relationships",
  "Only ONE id with the same value per document!",
  "Someone figures out the specificity before you even started",
  "You messed up"
]
*/

/*
const week3Phrases = [
  `The Golden Rule: Seperation of Concerns
  👑👑👑`,
  'Someone preemptively types "organization" in the chat 👩🏽‍💻',
  "CSS goes in a separate file",
  "Don't know? Go to the MDN!",
  "Get your selector relationships in order",
  "Only ONE id with the same value per document!",
  "Someone figures out the specificity before you even start",
  "Cascade - lower rules can override the ones above!",
  "The Box Model:  Content > Padding > Border > Margin",
  "We all float down here; you'll float too 🎈🎈🎈",
  "Get your shit together UPS",
  "Fluid: EVERYTHING IS A PERCENTAGE %%%",
  "Ems and Rems keep your font sizes elastic",
  "Flexbox is magic, y'all ✨✨✨",
  `<a href="http://css-tricks.com">css-tricks.com</a>: your CSS bible`,
  "Tried to use a media query without viewport <meta> tag",
  "Make good content decisions",
  "Today's stranger is tomorrow's coworker",
  "Insert unpaid meetup.com advertisement",
  "A lime alien that will haunt your dreams",
  "Spaced follow-up is important"
]
*/

// const week4Phrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   "Get your selector relationships in order",
//   "Only ONE id with the same value per document!",
//   "Someone figures out the specificity before you even start",
//   "Cascade - lower rules can override the ones above!",
//   "The Box Model:  Content > Padding > Border > Margin",
//   "We all float down here; you'll float too 🎈🎈🎈",
//   "Get your shit together UPS",
//   "Fluid: EVERYTHING IS A PERCENTAGE %%%",
//   "Ems and Rems keep your font sizes elastic",
//   "Flexbox is magic, y'all ✨✨✨",
//   `<a href="http://css-tricks.com">css-tricks.com</a>: your CSS bible`,
//   "Tried to use a media query without viewport <meta> tag",
//   "Make good content decisions",
//   "Stranger to coworker pipeline",
//   "Insert unpaid meetup.com advertisement",
//   "A lime alien that will life forever in your nightmares",
//   "Spaced follow-up is important",
//   "Progressive Enhancement",
//   "Khan Academy",
//   "Sh*t just got real 💩",
//   "Boats and logs 🚣🏽‍♀️",
//   "Make layouts 5-8 mobile responsive! 📱"
// ];

// const weekSevenPhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Stranger to coworker pipeline",
//   // "Insert unpaid meetup.com advertisement",
//   // "Computers do what you tell them to do",
//   // "Variables are buckets",
//   // "binary, upload, boom 👽",
//   // `Syntax:
//   // Spelling and Grammar rules`,
//   // "Declaration and then Assignment",
//   // "camelCase isOurConvention",
//   // "Leon misspelled 'oven'",
//   // "Everyone freaks out about operators",
//   "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "You come to the realization that Leon is NOT a lawyer ⚖️",
//   "Build an online presence",
//   "Unless you're a designer, use a portfolio template",
//   "Don't freelance without a contract! 📝",
//   "Under promise, over deliver! 📦"
// ];

// const weekEightPhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Computers do what you tell them to do",
//   "Variables are buckets",
//   "binary, upload, boom 👽",
//   `Syntax:
//   Spelling and Grammar rules`,
//   "Declaration and then Assignment",
//   "Everyone freaks out about operators",
//   // "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "Leon reveals house-specific office hours!",
//   "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by Feb 2!",
//   "Welcome back, we missed you! <br> Have a free space for being awesome! 😊"
// ];

// const weekNinePhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Computers do what you tell them to do",
//   "Variables are buckets",
//   // "binary, upload, boom 👽",
//   `Syntax:
//   Spelling and Grammar rules`,
//   "Declaration and then Assignment",
//   "Everyone freaks out about operators",
//   // "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   // "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by Feb 2!",
//   "Happy birthday, Alissa! 🎂",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎"
// ];

// const weekTenPhrases = [
//   // `The Golden Rule: Seperation of Concerns
//   // 👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by March 2!",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects!",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope!"
// ];

// const weekly11Phrases = [
//   // `The Golden Rule: Seperation of Concerns
//   // 👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   // "multiple conditions? Use && or ||",
//   "Beware the trough of sorrow!",
//   "Get a paid client by March 2!",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "Live portfolio review Friday @ 6:30EST! 🎙️",
//   "Leon announces the sponsor 🥳",
//   "Leon drops that sweet !Merch 👙",
//   "constructors are like factories 🏭",
//   "A prototype is another object that is used as a fallback source of properties",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API"
// ];

// const weekly12Phrases = [
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "Beware the trough of sorrow!",
//   "Don't forget to take care of your health! 💗",
//   "Repetition Repetition Repetition Repetition Repetition Repetition",
//   "Resetting the Forgetting Curve 😱",
//   "Let's GIT it on! 🥊",
//   "pwd shows where you are 📍",
//   "mkdir to create a new folder 📁",
//   "Git is a version control system",
//   "Save yourself by taking a snapshot(commit) in git 📸",
//   "You successfully installed git 🙌",
//   "Not sure what's in staging? git status",
//   "Uses branches so you don't BORK all your code 🐶",
//   "Github is more than backups!",
//   "You push a new repo",
//   "You can host with Github pages 🌐",
//   "Raffle time 🏆 Thanks for the swag, Microsoft!",
//   "Show all files in a folder using ls",
//   "remove a file with rm",
//   "git init creates a special folder to hold your commits",
//   "git add. adds everything to the staging area ➡️",
//   "don't be afraid to commit 💍"
// ];

// const weekly13Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "Live portfolio review Friday @ 6:30EST! 🎙️",
//   "Leon announces the sponsor 🥳",
//   "constructors are like factories 🏭",
//   "A prototype is another object that is used as a fallback source of properties",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "array.length lets you know how many elements are in your array",
//   "APIs are like restaurant menus",
//   "You can use local storage to store data across browser sessions! 💾"
// ];

// const weekl14Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "array.length lets you know how many elements are in your array",
//   "APIs are like restaurant menus",
//   "You can use local storage to store data across browser sessions! 💾",
//   "Bob and Nun emotes are here! Thanks, Wil!",
//   "Make sure to join our Code Wars clan ⚔️",
//   "Git Bowl this Saturday!",
//   "No class next week! 🗓️",
//   "Leon tells us about the new puppy 🐾",
//   "Contact NASA immediately! 🚀",
//   "War were declared 🃏"
// ];

// const week14bPhrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "APIs are like restaurant menus",
//   "Make sure to join our Code Wars clan ⚔️",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "The constructor keyword is used when you make a class",
//   "You create a detailed Pokemon class",
//   "You figure out how many rare candies you need to evolve your Pokemon 🍬"
// ];

// const week15Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   // "WHAT IS A STOPWATCH EVEN?",
//   // "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   // "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   // "Make sure you're using the right query parameters on your API",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Office hours moved to Sunday @ 1pm EST! 🕐",
//   "NERD FIGHT!!!! 👊🤓",
//   "The constructor keyword is used when you make a class",
//   "Construct an espresso machine ☕",
//   "OOP helps you understand existing code and add your own stuff with ease",
//   "Fuse data and functionality into one object with encapsulation, 👶🏾!",
//   "Want to hide details and show essentials? That's abstraction, 👶🏽!",
//   "WHAT WAS THE REASON?!"
// ];

// const week15bPhrases = [
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   // "WHAT IS A STOPWATCH EVEN?",
//   // "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Office hours moved to Sunday @ 1pm EST! 🕐",
//   "NERD FIGHT!!!! 👊🤓",
//   "The constructor keyword is used when you make a class",
//   "OOP helps you understand existing code and add your own stuff with ease",
//   "Fuse data and functionality into one object with encapsulation, 👶🏾!",
//   "Want to hide details and show essentials? That's abstraction, 👶🏽!",
//   "WHAT WAS THE REASON?!",
//   "You successfully create a class and extend it ",
//   "Networking starts up again next week",
//   "Inheritance lets us eliminate redundant code ",
//   "Yo dawg, I heard you like classes",
//   "We can use for...of in place of if/else and switch cases!"
// ];

// const week16Phrases = [
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "Classes are like templates for objects! 🧬",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Office hours moved to Sunday @ 1pm EST! 🕐",
//   "NERD FIGHT!!!! 👊🤓",
//   "The constructor keyword is used when you make a class",
//   "OOP helps you understand existing code and add your own stuff with ease",
//   "Fuse data and functionality into one object with encapsulation, 👶🏾!",
//   "Want to hide details and show essentials? That's abstraction, 👶🏽!",
//   "Creating new objects based on old ones? That's inheritance, 👶🏿",
//   "Want your code to work with a bunch of different objects? That's polymorphism, 👶🏻",
//   "Polymorphism allows us to override a method in every child class so it will do what we want",
//   "WHAT WAS THE REASON?! 🗣️",
//   "You successfully create a class and extend it ",
//   "Networking starts up again next week",
//   "Inheritance lets us eliminate redundant code ",
//   "Yo dawg, I heard you like classes",
//   "We can use for...of in place of if/else and switch cases!",
//   "You use encapsulation, abstraction, inheritance, and polymorphism 🦸🏾",
//   "Client deadline March 16th",
//   "Leon shares the big news! 😲"
// ];
// const week17aPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Crafting your story this Friday at 6:30pm EST! 📓",
//   "Review class this Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "NERD FIGHT!!!! 👊🤓",
//   "Client deadline March 16th",
//   "Don't forget to do your spaced repetition! 🔁",
//   "Use the form to join the Stream Team",
//   "Make sure to use The Checklist ✅",
//   "Make use of your Portfolio, Twitter, & LinkedIn 📁",
//   "You endorse at least 5 peers on LinkedIn",
//   "HITLIST is one of the most important career tools you have! 🎯",
//   "Each app should have a custom resume, cover letter, and story ",
//   "Take your interviewing skills to the BANK! 🏦",
//   "NO TIME TO BE HUMBLE DURING THE HUNT! 🤭",
//   "PREP for whiteboarding... Parameters, Returns, Examples, Pseudo Code",
//   "EUE during the interview... Explanation, Use, Example",
//   "Use CAR for the behavioral interview... Cause, Action Result",
//   "Your 100 Hours project should tie your past to present and show you can code ",
//   "Recruiters love 🟩",
//   "Research the company's process BEFORE the interview",
//   "Follow 50 engineers where you will be applying"
// ];
// const week17bPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live PREP class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "NERD FIGHT!!!! 👊🤓",
//   "You make an API request using async await",
//   "We were using APIs all along! 🤯",
//   "Don't forget to sign up for the Stream Team! 📹",
//   "Submit your checklist, 100 Hours Project, and Code Wars",
//   "JavaScript is single-threaded 🧵",
//   "Asyn allows us to continue using the app while operations are processed asyncronously",
//   "DOM is an API used to manipulate HTML/XML documents",
//   "We handle Web API responses with callbacks, promises, and async/await 📮",
//   "Higher Order Functions: function that takes another function as an argument",
//   "A Callback is a function that has be passed as an argument ☎️",
//   "Promises help us avoid Callback Hell 😈",
//   "Await waits for an async process to complete inside an Async Function",
//   "JS is sandboxed in the browser",
//   "Servers need disk access and network access 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️"
// ];

// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live PREP class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "NERD FIGHT!!!! 👊🤓",
//   "Get in that spaced repetition!",
//   "You make an API request using async await",
//   "We were using APIs all along! 🤯",
//   "Don't forget to sign up for the Stream Team! 📹",
//   "Submit your checklist, 100 Hours Project, and Code Wars",
//   "JavaScript is single-threaded 🧵",
//   "Asyn allows us to continue using the app while operations are processed asyncronously",
//   "DOM is an API used to manipulate HTML/XML documents",
//   "We handle Web API responses with callbacks, promises, and async/await 📮",
//   "Higher Order Functions: function that takes another function as an argument",
//   "A Callback is a function that has be passed as an argument ☎️",
//   "Promises help us avoid Callback Hell 😈",
//   "Await waits for an async process to complete inside an Async Function ⏳",
//   "JS is sandboxed in the browser",
//   "Servers need disk access and network access 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "The JavaScript is a lie! 🤥",
//   ".then() is a promise object that runs after the promise 'resolves'",
//   "Queues are FIFO (first in first out) structures",
//   "Callstack is a LIFO (last in first out) structure 🥞",
//   "You just got GOT!",
//   "JS is a language that can only do what the hosting environment allows 🌱",
//   "The same 💩 that lets you run JS in the browser can be used to run JS on servers, desktops, etc.",
//   "Clean up your back end! 🧼"
// ];

// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Tech Interveiw class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "NERD FIGHT!!!! 👊🤓",
//   "Get in that spaced repetition!",
//   "JavaScript is single-threaded 🧵",
//   "Higher Order Functions: function that takes another function as an argument",
//   "A Callback is a function that has be passed as an argument ☎️",
//   "Servers need disk access and network access 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Queues are FIFO (first in first out) structures",
//   "Callstack is a LIFO (last in first out) structure 🥞",
//   "You just got GOT!",
//   "JS is a language that can only do what the hosting environment allows 🌱",
//   "The same 💩 that lets you run JS in the browser can be used to run JS on servers, desktops, etc.",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js",
//   "Follow the key steps when making your API "
// ];

// const week19Phrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Live Tech Interveiw class this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "Servers need disk access(FS) and network access(HTTP) 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js 🖼️",
//   "Follow the key steps when making your API 🔑",
//   "How does the internet work?",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "Push your server to Heroku",
//   "Start prepping THE BANK! 🏦"
// ];
// const week19aPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Project Night this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "Servers need disk access(FS) and network access(HTTP) 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js 🖼️",
//   "Follow the key steps when making your API 🔑",
//   "How does the internet work?",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "Push your server to Heroku",
//   "Start prepping THE BANK! 🏦"
// ];
// const week20Phrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Project Night this Friday at 6:30pm EST! 📓",
//   "Office hours Sunday @ 1pm EST! 🕐",
//   "CRUD review Monday @ 6:30EST",
//   "One coffee chat this week! ☕",
//   "Microsoft sponsored stream next Tuesday!",
//   "Servers need disk access(FS) and network access(HTTP) 🌐",
//   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine ⚙️",
//   "Get your custom modules at NPM 📦",
//   "You build your very own simple Node server! 🛠️",
//   "Clean up your back end! 🧼",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Express is a framework for Node.js 🖼️",
//   "Follow the key steps when making your API 🔑",
//   "How does the internet work?",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "Push your server to Heroku",
//   "Start prepping THE BANK! 🏦",
//   "It's not too late!",
//   "Make a .env file and .gitignore to protect sensitive data"
// ];
// const week20bPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Don't forget to take care of yourself! 🛀",
//   "Get in that active recall and spaced repetition! 🔁",
//   "7 people from 100 Devs already have a job! 🤩",
//   "Microsoft Azure is a real one 🪟",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "Follow the key steps when making your Passport/Express app 🔑",
//   "How does the internet work? 🌐",
//   "The developer creates the API on the server and allows the clinet to talk to it. 💭",
//   "MongoDB stores your collections 🗄️",
//   "EJS is a simple templating language that lets you generate HTML markup with plain JavaScript",
//   "It's not too late! ⏳",
//   "Authentification = ability for users to login ✅",
//   "Microsoft Identity helps make signing in to your web apps easier",
//   "Azure Active Directory B2C lets you manage access on customer facing apps 🖥️",
//   "Mongoose provides a schema-based solution to model your app data",
//   "Models = fancy constructors complied from Schema definitions 🖼️",
//   "Passport = auth middleware for Node 🛂",
//   "MVC is a way to structure and organize our apps 🗂️"
// ];
// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Don't forget to take care of yourself! 🛀",
//   "Get in that active recall and spaced repetition! 🔁",
//   "7 people from 100 Devs already have a job! 🤩",
//   "Microsoft Azure is a real one 🪟",
//   "Follow the key steps when making your Passport/Express app 🔑",
//   "MongoDB stores your collections 🗄️",
//   "It's not too late! ⏳",
//   "Authentification = ability for users to login ✅",
//   "Microsoft Identity helps make sure you're not getting GOT by cyber security 🛡️",
//   "Azure Active Directory B2C lets you manage access on customer facing apps 🖥️",
//   "Mongoose provides a schema-based solution to model your app data",
//   "Models = fancy constructors complied from Schema definitions 🖼️",
//   "Passport = auth middleware for Node 🛂",
//   "MVC is a way to structure and organize our apps 🗂️",
//   "We don't get got, we go get 😎",
//   "You sign up for Microsoft 365 Developer Program (free!)",
//   "Passport has strategies 💡",
//   "Cookies store a session id in the user's browser to remember preferences 🍪"
// ];
// const weeklyPhrases = [
//   "Leon tells us about THE MACHINE 🐾",
//   "Backend review class Sunday @ 1pm EST",
//   "Stream & Blog team meeting @ 6:30pm EST",
//   "Team project next week! 🤝",
//   "Keep up with your networking 💬",
//   "100 hours project due Tuesday 6/1",
//   "Checklist due Tuesday 4/27 ✅",
//   "Team project due Tuesday 5/4",
//   "Hitlist due Tuesday 5/11 🎯",
//   "Don't forget to take care of yourself! 🛀",
//   "Keep pushing every day 🟩",
//   "10 premium job applications due Tuesday 6/15 📝",
//   "Prep the bank 🏦"
// ];

// const weeklyPhrases = [
//   "Team project due Thursday! 🤝",
//   "Keep up with your networking 💬",
//   "Keep pushing every day 🟩",
//   "Leon tells us about THE MACHINE 🐾",
//   "Don't forget to take care of yourself! 🛀",
//   "Get in that active recall and spaced repetition! 🔁",
//   "Follow the key steps when making your Passport/Express app 🔑",
//   "MongoDB stores your collections 🗄️",
//   "Authentification = ability for users to login ✅",
//   "Azure Active Directory B2C lets you manage access on customer facing apps 🖥️",
//   "Mongoose provides a schema-based solution to model your app data",
//   "Models = fancy constructors complied from Schema definitions 🖼️",
//   "Passport = auth middleware for Node 🛂",
//   "MVC is a way to structure and organize our apps 🗂️",
//   "We don't get got, we go get 😎",
//   "Passport has strategies 💡",
//   "Cookies store a session id in the user's browser to remember preferences 🍪",
//   "Queues are FIFO (first in first out) structures",
//   "Callstack is a LIFO (last in first out) structure 🥞",
//   "CRUD: Create(POST), Read(GET), Update(PUT), Delete(DELETE)",
//   "A wild Christos appears!",
//   "Take your interviewing skills to the BANK! 🏦",
//   "NO TIME TO BE HUMBLE DURING THE HUNT! 🤭",
//   "PREP for whiteboarding... Parameters, Returns, Examples, Pseudo Code",
//   "EUE during the interview... Explanation, Use, Example",
//   "Use CAR for the behavioral interview... Cause, Action Result"
// ];
// const weeklyPhrases = [
//   "Stream & Blog team meeting @ 6:30pm EST 🎬",
//   "Backend review class Sunday @ 1pm EST",
//   "Research string methods ",
//   "1 coffee chat and 3 connections each week! 💬",
//   "Keep pushing every day 🟩",
//   "Leon tells us about THE MACHINE 🐾",
//   "Don't forget to take care of yourself! 🛀",
//   "100 hours project MVP due Tuesday 6/1",
//   "Destructuring lets us extract data from arrays/objects and assign them to variables",
//   "The spread operator (...) takes an iterables and expands them into individual elements",
//   "When the state object changes, the component REACTS and re-renders",
//   "React is a library for handling your UI ⚛️",
//   "Components are reusable and extendable elements 🧩",
//   "react - creates components using APIs 🔧",
//   "react-dom - contains APIs for rendering to the browser DOM 🖥️",
//   "JSX is a syntax extension to JS that makes it easier to create elements in React 🏗️",
//   "Props are arguments passed into React Components",
//   "Client signatures/Approved PR due 6/1!",
//   "Classes are like templates for objects"
// ];

// const weeklyPhrases = [
//   "Don't forget to take care of yourself! 🛀",
//   'You ARE ready! 🚀',
//   'Tea Spill Friday @ 6:30pm ET ☕',
//   'Office Hours Sunday @ 1pm ET 🏢',
//   'Come to Standup M-F @ 6pm ET 🎙️',
//   'Sign up for your 1-on-1!',
//   "Don't forget about The Checklist ☑️",
//   'Craft your story 📖',
//   'Your HITLIST is your best friend 🎯',
//   'Use the cheat codes that Leon gave us! 🎮',
//   "If you're not a designer, USE A TEMPLATE!",
//   'Keep pushing every day 🟩',
//   "It's not stalking, it's networking 🤝",
//   'Take it to THE BANK 🏦',
//   'An algorithm is just the steps you take to solve a problem 🧮',
//   'Some algorithms are more efficient than others',
//   'Space: how much memory is being used 🌌',
//   'Time: how many operations are executed per input ⏱️',
//   'We can talk about efficiency of a soution with Big-O Notation',
//   'O(n^2) = quadratic, ex: nested loop ➿',
//   'O(n) = linear, ex: loop ➰',
//   'O(log n) = logarithmic, ex: divide and conquer ➗',
//   'O(1) = constant, ex: index lookup 📇'
// ];

// ***COHORT 2***

// JAN 18 2022
// const weeklyPhrases = [
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'angry Shia LaBeouf',
//   'Hello world!',
//   "Size doesn't matter, okay? OKAY???",
//   'CSS is about <em>style</em>',
//   'Ordered List',
//   'Unordered List',
//   `Syntax:
//      Spelling and Grammar rules`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   'Resetting the Forgetting Curve 😱',
//   'What should go in the head tag?',
//   'anchor tags are for links ⚓',
//   'Progressive Enhancement',
//   'Make sure to finish Learning How to Learn on Coursera!',
//   "Don't forget to agree to the rules on Discord ✅",
//   "Don't ask to ask 🙋🏾‍♂️",
//   'Use threads in help channels 🧵',
//   'Is this the most supportive message I can send in this moment? 👐',
//   'Trough of Sorrow 😭',
//   'You practiced active recall and space repetition ⏳',
//   'NERD FIGHT! 🤓'
// ];

// JAN 20 2022

// const weeklyPhrases = [
//   'You remembered to check in on Twitter',
//   'You responded in a discord message thread 🧵',
//   'Use keybr to increase typing speed! ⌨️',
//   'Go deep, NOT wide! ↕️',
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS declarations go inside curly braces {}',
//   'CSS is read from top to bottom',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   `Syntax:
//      Spelling and Grammar rules`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   'Resetting the Forgetting Curve 📉',
//   'What should go in the head tag? 🗣️',
//   'anchor tags are for links ⚓',
//   '#specificity .matters',
//   'Someone figures out the specificity before you even start',
//   'Progressive Enhancement',
//   'You finished Learning How to Learn on Coursera 🧠',
//   "Don't forget to agree to the rules on Discord ✅",
//   'You practiced active recall and space repetition ⏳'
// ];

// JAN 25 2022
// const weeklyPhrases = [
//   'You submitted your HTML homework to Glitch',
//   'Alumni Twitter Space this Friday 1.28 @ 6pm EST 🎓',
//   "You're keeping up with Anki 🗃️",
//   "Y'all nasty with your vomit code 🤮",
//   'You responded in a discord message thread 🧵',
//   'Use keybr to increase typing speed! ⌨️',
//   'Go deep, NOT wide! ↕️',
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS declarations go inside curly braces {}',
//   'CSS is read from top to bottom (cascade)',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   `Syntax:
//      Spelling and Grammar rules`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   'Resetting the Forgetting Curve 📉',
//   '#specificity .matters',
//   'Someone figures out the specificity before you even start',
//   'You finished Learning How to Learn on Coursera 🧠',
//   'You practiced active recall and space repetition ⏳',
//   'The Box Model has four properties 📦',
//   'We all float down here! 🎈',
//   'You survive 15 minutes of PAIN ⚡'
// ];

// JAN 27 2022
// const weeklyPhrases = [
//   'You submitted your HTML homework to Glitch',
//   'Alumni Twitter Space this Friday 1/28 @ 6pm EST 🎓',
//   "You're keeping up with Anki 🗃️",
//   'Get some sleep! 💤',
//   'You responded in a discord message thread 🧵',
//   'Use keybr to increase typing speed! ⌨️',
//   'Go deep, NOT wide! ↕️',
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS declarations go inside curly braces {}',
//   'CSS is read from top to bottom (cascade)',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   `Syntax:
//      Spelling and Grammar rules`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   'Resetting the Forgetting Curve 📉',
//   '#specificity .matters',
//   'Someone figures out the specificity before you even start',
//   'You finished Learning How to Learn on Coursera 🧠',
//   'You practiced active recall and space repetition ⏳',
//   'The Box Model has four properties 📦',
//   'We all float down here! 🎈',
//   'You survive 15 minutes of PAIN ⚡',
//   "Size doesn't matter, okay? OKAY???",
//   'Use media queries to make site responsive 📏',
//   "Don't forget to fill out the study group survey! ✍🏽"
// ];

// FEB 1 2022
// const weeklyPhrases = [
//   'You submitted your Study Community Survey',
//   'Get ready to network! 🕸️',
//   "Treat networking like you're making friends first 🤝",
//   'Research events/conferences to engage with folx in tech',
//   'Follow up: Meet ➡️ Email ➡️ LinkedIn ➡️ Twitter',
//   'Use the sheeeet to track netwoking 📝',
//   "You're keeping up with Anki 🗃️",
//   'You responded in a discord message thread 🧵',
//   'Go deep, NOT wide! ↕️',
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS declarations go inside curly braces {}',
//   'CSS is read from top to bottom (cascade)',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   'Resetting the Forgetting Curve 📉',
//   '#specificity .matters',
//   'You practiced active recall and space repetition ⏳',
//   'The Box Model has four properties 📦',
//   'We all float down here! 🎈',
//   'Use media queries to make site responsive 📏',
//   'You attempted the simple layouts 📰',
//   'Fluid = %',
//   'Elastic = EM & REM',
//   'Content Decisions = Media Queries',
//   "Don't forget to add a meta tag for the viewport 👀",
//   'Flexbox is MAGIC! 🪄'
// ];

// FEB 3 2022
// const weeklyPhrases = [
//   'You submitted your Study Community Survey',
//   'You made your 15 minutes of pain responsive',
//   'Get ready to network! 🕸️',
//   "Let's write some BADD code!",
//   "Treat networking like you're making friends first 🤝",
//   'Progressive Enhancement',
//   'Follow up: Meet ➡️ Email ➡️ LinkedIn ➡️ Twitter',
//   'Use the sheeeet to track netwoking 📝',
//   "You're keeping up with Anki 🗃️",
//   'You responded in a discord message thread 🧵',
//   'Go deep, NOT wide! ↕️',
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS declarations go inside curly braces {}',
//   'CSS is read from top to bottom (cascade)',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   '#specificity .matters',
//   'You practiced active recall and space repetition ⏳',
//   'The Box Model has four properties 📦',
//   'We all float down here! 🎈',
//   'Use media queries to make site responsive 📏',
//   'Fluid = %',
//   'Elastic = EM & REM',
//   'Content Decisions = Media Queries',
//   "Don't forget to add a meta tag for the viewport 👀",
//   'Flexbox is MAGIC! 🪄'
// ];

// FEB 10 2022
// const weeklyPhrases = [
//   'You submitted your Study Community Survey',
//   "You're signed up for Leon's newsletter",
//   "You're taking care of yourself 🛀🏾",
//   'Make your work better 🏆',
//   "You've already started using the SHEEEEEET",
//   'Coding challenges start next week!',
//   'Get a paid client by March 29th 🤑',
//   'You completed all the layouts',
//   '💩 just got real',
//   'DIG DEEP!',
//   "Who's going to carry the ⛵ and 🪵?",
//   "Treat networking like you're making friends first 🤝",
//   'Progressive Enhancement',
//   'Follow up: Meet ➡️ Email ➡️ LinkedIn ➡️ Twitter',
//   "You're keeping up with Anki 🗃️",
//   'The Golden Rule 👑👑👑',
//   'What is the internet? 💻 🖥️',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS declarations go inside curly braces {}',
//   'CSS is read from top to bottom (cascade)',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   '#specificity .matters',
//   'You practiced active recall and space repetition ⏳',
//   'The Box Model has four properties 📦',
//   'We all float down here! 🎈',
//   'Use media queries to make site responsive 📏',
//   'Fluid = %',
//   'Elastic = EM & REM',
//   'Content Decisions = Media Queries',
//   "Don't forget to add a meta tag for the viewport 👀",
//   'Flexbox is MAGIC! 🪄'
// ];

// FEB 15 2022
// const weeklyPhrases = [
//   'You submitted your Study Community Survey',
//   "You're taking care of yourself 🛀🏾",
//   'Make your work better 🏆',
//   "You've already started using the SHEEEEEET",
//   'Coding challenges start after Thursday! 🧩',
//   'Get a paid client by March 29th 🤑',
//   'You completed all the layouts',
//   '💩 just got real',
//   "Who's going to carry the ⛵ and 🪵?",
//   "You've had at least one coffee chat ☕",
//   'Progressive Enhancement',
//   'Follow up: Meet ➡️ Email ➡️ LinkedIn ➡️ Twitter',
//   "You're keeping up with Anki 🗃️",
//   'The Golden Rule 👑👑👑',
//   'CSS is about <em>style</em> 💅🏿',
//   'CSS is read from top to bottom (cascade)',
//   'Use a separate CSS file and link in your <head> ',
//   "Don't know? Go to the MDN!",
//   'parent > child to target direct descendents 👶🏽',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   '#specificity .matters',
//   'You practiced active recall and space repetition ⏳',
//   'The Box Model has four properties 📦',
//   'We all float down here! 🎈',
//   'Use media queries to make site responsive 📏',
//   'Fluid = %',
//   'Elastic = EM & REM',
//   'Content Decisions = Media Queries',
//   "Don't forget to add a meta tag for the viewport 👀",
//   'Flexbox is MAGIC! 🪄',
//   "Go deep on things that don't make sense 🤔"
// ];

// FEB 17, 2022
// const weeklyPhrases = [
//   'You submitted your Study Community Survey',
//   'Half hard work, half believing you can do it',
//   "You're taking care of yourself 🛀🏾",
//   'Make your work better 🏆',
//   "You've already started using the SHEEEEEET",
//   'Coding challenges start after Thursday! 🧩',
//   'Get a paid client by March 29th 🤑',
//   'You completed all the layouts',
//   '💩 just got real',
//   "You've had at least one coffee chat ☕",
//   "You're keeping up with Anki 🗃️",
//   'The Golden Rule 👑👑👑',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   '#specificity .matters',
//   'You practiced active recall and space repetition ⏳',
//   'A computer will do what you tell it to do',
//   'Programming = writing instructions in a language a computer can understand',
//   'Binary Upload Boom (BUB) 👽',
//   `Syntax:
//   Spelling and Grammar rules`,
//   'A variable is a bucket 🪣',
//   'camelCase is a variable convention 🐫',
//   `You can store different data types in variables
//   (let age = 25 )
//   `,
//   "Strings are text wrapped in quotes '🔤'",
//   'If statements are either true or false',
//   `Logical operators help you compare values
//       like x === 3`,
//   'Conditional syntax uses if, else if, and else statements 🕵️',
//   "Don't confuse assignment (=) and comparison (===)",
//   '|| is the OR operator',
//   'You code along in JavaScript 💻'
// ];

// feb 22 2022
// const weeklyPhrases = [
//   'You submitted your Study Community Survey',
//   'Half hard work, half believing you can do it',
//   "You're taking care of yourself 🛀🏾",
//   "You've already started using the SHEEEEEET",
//   'Coding challenges start after Thursday! 🧩',
//   'Get a paid client by March 29th 🤑',
//   'You completed all the layouts',
//   '💩 just got real',
//   "You've had at least one coffee chat ☕",
//   "You're keeping up with Anki 🗃️",
//   'The Golden Rule 👑👑👑',
//   'You practiced active recall and space repetition ⏳',
//   'A computer will do what you tell it to do',
//   'Programming = writing instructions in a language a computer can understand',
//   'Binary Upload Boom (BUB) 👽',
//   `Syntax:
//   Spelling and Grammar rules`,
//   'A variable is a bucket 🪣',
//   'camelCase is a variable convention 🐫',
//   `You can store different data types in variables
//   (let age = 25 )
//   `,
//   "Strings are text wrapped in quotes '🔤'",
//   'If statements are either true or false',
//   `Logical operators help you compare values
//       like x === 3`,
//   'Floating numbers have a decimal',
//   'Conditional syntax uses if, else if, and else statements 🕵️',
//   "Don't confuse assignment (=) and comparison (===)",
//   '|| is the OR operator',
//   'You code along in JavaScript 💻',
//   'Modulus %',
//   '== compares only value,  === compares value AND type',
//   '&& is the AND operator',
//   'Multiple conditions?    Use && or || '
// ];

// MAR 1 2022
// const weeklyPhrases = [
//   'Study Community networking March 8th',
//   'I am not a lawyer ⚖️',
//   'I am not a tax professional 🧮',
//   'Freelancing helps you earn money and gain experience 🏦',
//   'Get rid of that boot camp stink 🦨',
//   'Pay yo taxes! 💰',
//   'Build an online persona 🥸',
//   'Portfolio, LinkedIn, Twitter',
//   "If you're not a designer, use a template! 🖼️",
//   'Host your portfolio on Netlify for free',
//   'Start close when finding clients 👪',
//   "You've already started using the SHEEEEEET",
//   'Pick a niche',
//   'Get a deposit 📩',
//   'Upgrade your proposal after your first client 📝',
//   'Leave room to get help',
//   'Contracts protect BOTH parties 🤝🏾',
//   'Under promise, over deliver 📦',
//   'Get a paid client by March 29th 🤑',
//   "You've had at least one coffee chat ☕",
//   "You're keeping up with Anki 🗃️"
// ];

// MAR 3 2022
// const weeklyPhrases = [
//   'JavaScript should NOT make sense yet 🥔',
//   'You CAN and WILL do this! ✊',
//   'Leon will never ask you for money',
//   'Check out our stream team! 🎥',
//   'You sign up to join the stream team',
//   'Submit the best clip if you want to be fancy 📎',
//   'Study Community networking March 8th',
//   'Congrats on the best clip, Nikolaus#1985! 🏆',
//   'The Golden Rule: Seperation of Concerns 👑',
//   'Only one #ID with the same value per document!',
//   '.class is for multiple elements',
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   '#specificity .matters',
//   'A computer will do what you tell it to do',
//   'Programming = writing instructions in a language a computer can understand',
//   'Binary Upload Boom (BUB) 👽',
//   'Functions are reusuable sets of instructions',
//   'Functions are the building blocks of a program 🚧',
//   `Syntax:
//   Spelling and Grammar rules`,
//   'A variable is a bucket 🪣',
//   'camelCase is a variable convention 🐫',
//   `You can store different data types in variables
//   (let age = 25 )
//   `,
//   "Strings are text wrapped in quotes '🔤'",
//   'If statements are either true or false',
//   `Logical operators help you compare values
//       like x === 3`,
//   'Floating numbers have a decimal',
//   'Conditional syntax uses if, else if, and else statements 🕵️',
//   "Don't confuse assignment (=) and comparison (===)",
//   '|| is the OR operator',
//   'You code along in JavaScript 💻',
//   '== compares only value,  === compares value AND type',
//   '&& is the AND operator',
//   'Multiple conditions?    Use && or || ',
//   "You've had at least one coffee chat ☕",
//   "You're keeping up with Anki 🗃️"
// ];

// MAR 15 2022
// const weeklyPhrases = [
//   'You submitted your drafts and tasks in the form 📮',
//   "You've already started using the SHEEEEEET",
//   'Daily coding challenges starting! 🧩',
//   'Get a paid client by March 31st 🤑',
//   'JavaScript should NOT make sense yet 🥔',
//   'functions are the building blocks of a program 🧱',
//   'functions can take parameters and pass arguments',
//   'Submit the best clip if you want to be fancy 📎',
//   'A computer will do what you tell it to do',
//   'Programming = writing instructions in a language a computer can understand',
//   'Functions are reusuable sets of instructions',
//   `Syntax:
//   Spelling and Grammar rules`,
//   'A variable is a bucket 🪣',
//   'camelCase is a variable convention 🐫',
//   `You can store different data types in variables
//   (let age = 25 )
//   `,
//   'If statements are either true or false',
//   'Conditional syntax uses if, else if, and else statements 🕵️',
//   "Don't confuse assignment (=) and comparison (===)",
//   '|| is the OR operator',
//   'You code along in JavaScript 💻',
//   '== compares only value,  === compares value AND type',
//   '&& is the AND operator',
//   'Multiple conditions?    Use && or || ',
//   "You've had at least one coffee chat ☕",
//   "You're keeping up with Anki 🗃️",
//   'Loops repeat an action some number of times ➿',
//   'for, while, and do while are the main types of loops',
//   'Arrays are toasters 🍞',
//   'Arrays have a zero-based index 0️⃣,1️⃣,2️⃣',
//   'Arrays are a way to stored ordered collections',
//   'Array elements can be of any type',
//   'You can access and update elements in an array by their index position',
//   'Arrays have lots of useful methods built in! 🔧'
// ];
