const weeklyPhrases = [
  "Arrays are like Bill Gates' toaster",
  "Arrays are 0 indexed!",
  "Arrays have methods - check out the MDN! 🔎",
  "Don't forget to take care of your health! 💗",
  "Objects store 'keyed' collections 🔑",
  "Properties are attributes and methods are behavior (objects)",
  "excuse me sir, this is a car factory",
  "WHAT IS A STOPWATCH EVEN?",
  "every data type has a prototype",
  "EVERYTHING IS AN OBJECT!!1!!1!",
  "Classes are like templates for objects! 🧬",
  "APIs are a simple interface for some complex action",
  "Leon tries to make fetch happen 👚",
  "'this' is your scope, learn your scope! 🔬",
  "constructors are like factories 🏭",
  "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
  "Make sure you're using the right query parameters on your API",
  "APIs are like restaurant menus",
  "Make sure to join our Code Wars clan ⚔️",
  "Leon tells us about THE MACHINE 🐾",
  "Live Crafting your story this Friday at 6:30pm EST! 📓",
  "The constructor keyword is used when you make a class",
  "You create a detailed Pokemon class",
  "You figure out how many rare candies you need to evolve your Pokemon 🍬"
];
/*
const weekOnePhrases = [
    "The Golden Rule 👑👑👑",
    "What is the internet? 💻 🖥️",
    "angry Shia LaBeouf",
    "Hello world!",
    "Size doesn't matter, okay? OKAY???",
    "CSS is about <em>style</em>",
    "Ordered List",
    "Unordered List",
    `Syntax:
     Spelling and Grammar rules`,
    'Someone preemptively types "organization" in the chat 👩🏽‍💻',
    "Resetting the Forgetting Curve 😱",
    "What should go in the head tag?",
    "anchor tags are for links ⚓",
    "Progressive Enhancement"
  ]
*/

/*
const weekTwoPhrases = [
  "The Golden Rule: Seperation of Concerns 👑👑👑",
  "What is the internet? 💻 🖥️",
  "Hello twitch!",
  `Syntax:
   Spelling and Grammar rules`,
  'Someone preemptively types "organization" in the chat 👩🏽‍💻',
  "Resetting the Forgetting Curve 😱",
  "Progressive Enhancement!",
  // "Everyone freaks out about operators",
  "Repetition Repetition Repetition Repetition Repetition Repetition",
  "CSS link goes in the head 🗣️",
  "Don't know? Go to the MDN!",
  "Selectors are about relationships",
  "Only ONE id with the same value per document!",
  "Someone figures out the specificity before you even started",
  "You messed up"
]
*/

/*
const week3Phrases = [
  `The Golden Rule: Seperation of Concerns
  👑👑👑`,
  'Someone preemptively types "organization" in the chat 👩🏽‍💻',
  "CSS goes in a separate file",
  "Don't know? Go to the MDN!",
  "Get your selector relationships in order",
  "Only ONE id with the same value per document!",
  "Someone figures out the specificity before you even start",
  "Cascade - lower rules can override the ones above!",
  "The Box Model:  Content > Padding > Border > Margin",
  "We all float down here; you'll float too 🎈🎈🎈",
  "Get your shit together UPS",
  "Fluid: EVERYTHING IS A PERCENTAGE %%%",
  "Ems and Rems keep your font sizes elastic",
  "Flexbox is magic, y'all ✨✨✨",
  `<a href="http://css-tricks.com">css-tricks.com</a>: your CSS bible`,
  "Tried to use a media query without viewport <meta> tag",
  "Make good content decisions",
  "Today's stranger is tomorrow's coworker",
  "Insert unpaid meetup.com advertisement",
  "A lime alien that will haunt your dreams",
  "Spaced follow-up is important"
]
*/

// const week4Phrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   "Get your selector relationships in order",
//   "Only ONE id with the same value per document!",
//   "Someone figures out the specificity before you even start",
//   "Cascade - lower rules can override the ones above!",
//   "The Box Model:  Content > Padding > Border > Margin",
//   "We all float down here; you'll float too 🎈🎈🎈",
//   "Get your shit together UPS",
//   "Fluid: EVERYTHING IS A PERCENTAGE %%%",
//   "Ems and Rems keep your font sizes elastic",
//   "Flexbox is magic, y'all ✨✨✨",
//   `<a href="http://css-tricks.com">css-tricks.com</a>: your CSS bible`,
//   "Tried to use a media query without viewport <meta> tag",
//   "Make good content decisions",
//   "Stranger to coworker pipeline",
//   "Insert unpaid meetup.com advertisement",
//   "A lime alien that will life forever in your nightmares",
//   "Spaced follow-up is important",
//   "Progressive Enhancement",
//   "Khan Academy",
//   "Sh*t just got real 💩",
//   "Boats and logs 🚣🏽‍♀️",
//   "Make layouts 5-8 mobile responsive! 📱"
// ];

// const weekSevenPhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Stranger to coworker pipeline",
//   // "Insert unpaid meetup.com advertisement",
//   // "Computers do what you tell them to do",
//   // "Variables are buckets",
//   // "binary, upload, boom 👽",
//   // `Syntax:
//   // Spelling and Grammar rules`,
//   // "Declaration and then Assignment",
//   // "camelCase isOurConvention",
//   // "Leon misspelled 'oven'",
//   // "Everyone freaks out about operators",
//   "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "You come to the realization that Leon is NOT a lawyer ⚖️",
//   "Build an online presence",
//   "Unless you're a designer, use a portfolio template",
//   "Don't freelance without a contract! 📝",
//   "Under promise, over deliver! 📦"
// ];

// const weekEightPhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   "Don't know? Go to the MDN!",
//   "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Computers do what you tell them to do",
//   "Variables are buckets",
//   "binary, upload, boom 👽",
//   `Syntax:
//   Spelling and Grammar rules`,
//   "Declaration and then Assignment",
//   "Everyone freaks out about operators",
//   // "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "Leon reveals house-specific office hours!",
//   "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by Feb 2!",
//   "Welcome back, we missed you! <br> Have a free space for being awesome! 😊"
// ];

// const weekNinePhrases = [
//   `The Golden Rule: Seperation of Concerns
//   👑👑👑`,
//   'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "Make good content decisions",
//   "Computers do what you tell them to do",
//   "Variables are buckets",
//   // "binary, upload, boom 👽",
//   `Syntax:
//   Spelling and Grammar rules`,
//   "Declaration and then Assignment",
//   "Everyone freaks out about operators",
//   // "if(conditions mentioned){click!}",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   // "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by Feb 2!",
//   "Happy birthday, Alissa! 🎂",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎"
// ];

// const weekTenPhrases = [
//   // `The Golden Rule: Seperation of Concerns
//   // 👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   "multiple conditions? Use && or ||",
//   "Beware the trough of sorrow!",
//   "TURN IT UP!",
//   "Get a paid client by March 2!",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects!",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope!"
// ];

// const weekly11Phrases = [
//   // `The Golden Rule: Seperation of Concerns
//   // 👑👑👑`,
//   // 'Someone preemptively types "organization" in the chat 👩🏽‍💻',
//   // "Don't know? Go to the MDN!",
//   // "Only ONE id with the same value per document!",
//   "select my query!!!",
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "modulus % finds the remainder",
//   "BEWARE reassignment <br> ( = ) vs. comparison <br> ( ==/=== )",
//   "functions are the building blocks of a program 🧱",
//   "functions can take parameters and pass arguments",
//   // "multiple conditions? Use && or ||",
//   "Beware the trough of sorrow!",
//   "Get a paid client by March 2!",
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "Live portfolio review Friday @ 6:30EST! 🎙️",
//   "Leon announces the sponsor 🥳",
//   "Leon drops that sweet !Merch 👙",
//   "constructors are like factories 🏭",
//   "A prototype is another object that is used as a fallback source of properties",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API"
// ];

// const weekly12Phrases = [
//   "spend Jeff Bezos' money! 💸",
//   "Not that kind of stream, folx!",
//   "Beware the trough of sorrow!",
//   "Don't forget to take care of your health! 💗",
//   "Repetition Repetition Repetition Repetition Repetition Repetition",
//   "Resetting the Forgetting Curve 😱",
//   "Let's GIT it on! 🥊",
//   "pwd shows where you are 📍",
//   "mkdir to create a new folder 📁",
//   "Git is a version control system",
//   "Save yourself by taking a snapshot(commit) in git 📸",
//   "You successfully installed git 🙌",
//   "Not sure what's in staging? git status",
//   "Uses branches so you don't BORK all your code 🐶",
//   "Github is more than backups!",
//   "You push a new repo",
//   "You can host with Github pages 🌐",
//   "Raffle time 🏆 Thanks for the swag, Microsoft!",
//   "Show all files in a folder using ls",
//   "remove a file with rm",
//   "git init creates a special folder to hold your commits",
//   "git add. adds everything to the staging area ➡️",
//   "don't be afraid to commit 💍"
// ];

// const weekly13Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "Live portfolio review Friday @ 6:30EST! 🎙️",
//   "Leon announces the sponsor 🥳",
//   "constructors are like factories 🏭",
//   "A prototype is another object that is used as a fallback source of properties",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "array.length lets you know how many elements are in your array",
//   "APIs are like restaurant menus",
//   "You can use local storage to store data across browser sessions! 💾"
// ];

// const weekl14Phrases = [
//   "Arrays are like Bill Gates' toaster",
//   "Arrays are 0 indexed!",
//   "Arrays have methods - check out the MDN! 🔎",
//   "Don't forget to take care of your health! 💗",
//   "Objects store 'keyed' collections 🔑",
//   "Properties are attributes and methods are behavior (objects)",
//   "excuse me sir, this is a car factory",
//   "WHAT IS A STOPWATCH EVEN?",
//   "every data type has a prototype",
//   "EVERYTHING IS AN OBJECT!!1!!1!",
//   "Classes are like templates for objects! 🧬",
//   "APIs are a simple interface for some complex action",
//   "Leon tries to make fetch happen 👚",
//   "You create an object that has four properties and three methods",
//   "EVERYBODY! SHOTS! SHOTS! SHOTS!",
//   "'this' is your scope, learn your scope! 🔬",
//   "constructors are like factories 🏭",
//   "If grandma has a car, you have a car! 🚗 Thanks, inheritance!",
//   "Make sure you're using the right query parameters on your API",
//   "array.length lets you know how many elements are in your array",
//   "APIs are like restaurant menus",
//   "You can use local storage to store data across browser sessions! 💾",
//   "Bob and Nun emotes are here! Thanks, Wil!",
//   "Make sure to join our Code Wars clan ⚔️",
//   "Git Bowl this Saturday!",
//   "No class next week! 🗓️",
//   "Leon tells us about the new puppy 🐾",
//   "Contact NASA immediately! 🚀",
//   "War were declared 🃏"
// ];
